import React, { createContext, useState } from 'react';
import { Dimensions } from 'react-native';

// const screenWidth  = Math.round(Dimensions.get('window').width);//=>PEGANDO A LARGURA DA TELA
// const screenHeight = Math.round(Dimensions.get('window').height);

//TODOS PARAMETROS IMPORTANTES RELACIONADO A SITUAÇÃO DOS PRODUTOS ABAIXO
var OBJETOS_JSON =
{
    LIBERAR_GRAVACAO_TELEFONE_SEM_NUMERO: false,
    TELEFONE: "SEM_TELEFONE_USUARIO",

    LATITUDE: "",
    LONGITUDE: "",

    FAZER_PROPOSTA: "",
    NOTIFICACAO_RECEIVER_IDENTIFICACAO: "NENHUMA_NOTIFICACAO_AGORA",
    BUSCAR_POSTAGENS: "SIM",
    BUSCAR_NOTIFICACAO: true,
    BUSCAR_LICENCA: false,
    TELA_ATUAL: "Principal",
    TELA_ORIGEM: "nenhuma",
    TELA_TERCEIRA: "nenhuma",

    PROPOSTAS_RECEBIDAS: 0,
    PROPOSTAS_ENVIADAS: 0,
    PROPOSTAS_ACEITAS: 0,
    VENDAS_RECENTES: 0,

    PUBLICACOES_PENDENTES: 0,
    PUBLICACOES_EXPIRADAS: 0,


    ESTA_VENDIDO_OU_COMPRADO: "NAO",
    VENDA_OU_COMPRA_CONSUMADA: "NAO",

    CONEXAO_DO_APP: "OFF-LINE",
    NUMERO_IP: "",
    NUMERO_IP_API_MERCADOPAGO:"",


    TODOS_OS_PRODUTOS: "",
    PRODUTO_JSON_SENDO_MANIPULADO_ATUALMENTE: "",

    LISTAIMAGENS_CONTEXT: [],
    LISTAVIDEOS_CONTEXT: [],
    LISTA_THUMBAILS: [],


    // CONTADOR_GLOBAL: 60,
    CONTADOR_GLOBAL: 59,

    LICENCA_USO: "SEM_CADASTRO",

    LARGURA_DA_TELA: Math.round(Dimensions.get('window').width),
    ALTURA_DA_TELA: Math.round(Dimensions.get('window').height),

    SOMENTE_UMA_VEZ: true,
    QUANTIDADE_DE_POSTAGEMS: 0,

    PARAMETROS_QUANTIDADE_DE_POSTAGEMS: 2,// ESSA É A QUANTIDADE DE POSTAGEM GRATUITA PERMITIDA

    TABELA_PRECOS_ANUNCIO: null,

    tempoPostagem_G: 360,

    COBRANCA_APP_PUBLICACAO_OU_TAXA: "",

    DADOS_DA_NEGOCIACAO: "",

    INDICE_GLOBAL_IMAGENS_VIDEOS: -1,

    //  CONECTANDO_AO_BANCO_DE_DADOS_GLOBALMENTE:null

    PUBLICACAO_EM_PROCESSO: "NAO_ENVIADO", //STATUS POSSIVEIS => NAO_ENVIADO | ENVIANDO | ENVIADO

    COMPACTACAO_DE_VIDEO_ESTADO:false,
  
    STATUS_DA_VENDA_OU_COMPRA: "",


    URL_VIDEOS_DURANTE_POSTAGENS: [],
    URL_VIDEO_EXCLUIDO_DURANTE_POSTAGENS: "",
    INDICE_DO_VIDEO_EXCLUIR_DURANTE_POSTAGENS: -1,


};
/**/
//TODOS PARAMETROS IMPORTANTES RELACIONADO A SITUAÇÃO DOS PRODUTOS ACIMA



//const GlobalContext = createContext({VARIAVEL_GLOBAL: array}); 
const GlobalContext = createContext({ VARIAVEL_GLOBAL: OBJETOS_JSON });

export const Globalprovider = ({ children }) => (
    <GlobalContext.Provider value={{ VARIAVEL_GLOBAL: OBJETOS_JSON }} >
        {children}
    </GlobalContext.Provider>
);



export default GlobalContext;
